name: Validate

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
  # TODO: Test job
  
